In [10]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(a==7)
print(x)

(array([6]),)


In [12]:
import numpy as np
a=np.array([1,2,3,4])
x=np.where(a==7)
print(x)

(array([], dtype=int64),)


In [14]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(a%2==0)
y=np.where(a%3==1)
print(x)
print(y)

(array([1, 3, 5, 7, 9]),)
(array([0, 3, 6, 9]),)


In [16]:
import numpy as np
a=np.array([1,2,3,5,6])
x=np.searchsorted(a,5,side='left')
y=np.searchsorted(a,5,side='right')
print(x)
print(y)

3
4


In [19]:
import numpy as np
a=np.array([9,5,2,7,6,4])
print(np.sort(a))
b=np.array([[2,4,3],[5,9,10]])
print(np.sort(b))

[2 4 5 6 7 9]
[[ 2  3  4]
 [ 5  9 10]]


In [24]:
import numpy as np
a=np.array([31,78,69,88])
x=[True,True,False,True]
new=a[x]
print(x)
print(new)

[True, True, False, True]
[31 78 88]


In [25]:
import numpy as np
a=np.array([31,78,69,88])
filter_a=a>70
new=a[filter_a]
print(filter_a)
print(new)

[False  True False  True]
[78 88]
